"""Safety modules for the InSilico Clinical Trial Simulator.

Implements QTc exposure-response, DILI hazard, and CTCAE DLT grading.
All thresholds are configurable via YAML config files.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from insilico_trial.schemas import Drug, Observation, SafetyThresholds

# ---------------------------------------------------------------------------
# QTc Exposure-Response Module
# ---------------------------------------------------------------------------


@dataclass
class QTcResult:
    """Result of QTc safety assessment."""

    patient_id: str
    baseline_qtc: float  # ms
    max_qtc: float  # ms (baseline + max delta)
    qtc_delta: float  # ms (max - baseline)
    flag_qtc_60ms_delta: bool  # deltaQTc > 60 ms
    flag_qtc_500ms_absolute: bool  # absolute QTc > 500 ms


def assess_qtc(
    observations: list[Observation],
    drug: Drug,
    qt_threshold_delta: float = 60.0,
    qt_threshold_absolute: float = 500.0,
) -> list[QTcResult]:
    """Assess QTc prolongation risk from observation data.

    Reports baseline QTc, absolute QTc, and delta QTc (baseline + Emax effect
    from observed concentrations). Flags are set against the supplied
    thresholds (defaults: 60 ms delta / 500 ms absolute, per FDA guidance).

    Note: Hy's Law is a liver-safety concept and is deliberately NOT reported
    here; it belongs to the DILI module.
    """
    results: list[QTcResult] = []

    from collections import defaultdict

    patient_obs: dict[str, list[Observation]] = defaultdict(list)
    for obs in observations:
        patient_obs[obs.patient_id].append(obs)

    for patient_id, obs_list in patient_obs.items():
        baseline_qtc = drug.qtcd_baseline

        max_delta_qtc = 0.0
        for obs in obs_list:
            if obs.concentration is not None and obs.qt_interval is not None:
                # Use the observed QTc relative to baseline as the delta.
                delta_qtc = obs.qt_interval - baseline_qtc
            elif obs.concentration is not None and drug.qtcd_ec50 > 0:
                delta_qtc = drug.qtcd_emax * obs.concentration / (drug.qtcd_ec50 + obs.concentration)
            else:
                continue
            max_delta_qtc = max(max_delta_qtc, delta_qtc)

        max_qtc = baseline_qtc + max_delta_qtc
        results.append(QTcResult(
            patient_id=patient_id,
            baseline_qtc=baseline_qtc,
            max_qtc=max_qtc,
            qtc_delta=max_delta_qtc,
            flag_qtc_60ms_delta=max_delta_qtc > qt_threshold_delta,
            flag_qtc_500ms_absolute=max_qtc > qt_threshold_absolute,
        ))

    return results


# ---------------------------------------------------------------------------
# DILI Hazard Module
# ---------------------------------------------------------------------------

# Standard ULN values (CTCAE v5.0 reference)
ALT_ULN_UL = 40.0  # U/L, upper limit of normal for ALT
BILI_ULN_MGDL = 1.2  # mg/dL, upper limit of normal for total bilirubin


@dataclass
class DiliResult:
    """Result of DILI hazard assessment."""

    patient_id: str
    max_alt: float  # U/L (max ALT)
    max_bilirubin: float  # mg/dL (max bilirubin)
    alt_upper_3x_uln: bool  # ALT > 3x ULN
    bili_upper_2x_uln: bool  # Bilirubin > 2x ULN
    hy_law_criteria_met: bool  # Hy's Law: ALT > 3x ULN + Bilirubin > 2x ULN
    dili_probability: float  # Probability of DILI (0-1)


def assess_dili(
    observations: list[Observation],
    drug: Drug,
    alt_uln_mult: float = 3.0,
    bili_uln_mult: float = 2.0,
) -> list[DiliResult]:
    """Assess DILI (Drug-Induced Liver Injury) hazard from observation data.

    Uses the simulated ALT/bilirubin values (generated by the trial engine from
    liver exposure) to flag elevations relative to the thresholds (defaults:
    ALT > 3x ULN and bilirubin > 2x ULN, Hy's Law).
    """
    results: list[DiliResult] = []

    from collections import defaultdict

    patient_obs: dict[str, list[Observation]] = defaultdict(list)
    for obs in observations:
        patient_obs[obs.patient_id].append(obs)

    for patient_id, obs_list in patient_obs.items():
        max_alt = 0.0
        max_bilirubin = 0.0
        for obs in obs_list:
            if obs.alt is not None and obs.alt > max_alt:
                max_alt = obs.alt
            if obs.bilirubin is not None and obs.bilirubin > max_bilirubin:
                max_bilirubin = obs.bilirubin

        alt_3x_uln = max_alt > alt_uln_mult * ALT_ULN_UL
        bili_2x_uln = max_bilirubin > bili_uln_mult * BILI_ULN_MGDL
        hy_law = alt_3x_uln and bili_2x_uln

        dili_prob = drug.dili_risk
        if hy_law:
            dili_prob = min(0.5, drug.dili_risk * 10.0)

        results.append(DiliResult(
            patient_id=patient_id,
            max_alt=max_alt,
            max_bilirubin=max_bilirubin,
            alt_upper_3x_uln=alt_3x_uln,
            bili_upper_2x_uln=bili_2x_uln,
            hy_law_criteria_met=hy_law,
            dili_probability=dili_prob,
        ))

    return results


# ---------------------------------------------------------------------------
# CTCAE DLT Grading Module
# ---------------------------------------------------------------------------

CTCAE_GRADES = Literal[0, 1, 2, 3, 4, 5]


def ctcae_dlt_grade(
    exposure: float,
    dose: float,
    max_alt: float | None = None,
    max_bili: float | None = None,
    baseline_qtc: float | None = None,
    qtc_delta: float | None = None,
) -> int:
    """Grade adverse events using CTCAE v5.0 criteria for DLT assessment.

    Grades 3+ are generally considered dose-limiting in Phase I trials.
    """
    grade = 0

    # Hepatotoxicity grading per CTCAE v5.0 (ALT)
    if max_alt is not None:
        uln = ALT_ULN_UL
        if uln < max_alt <= 3 * uln:
            grade = max(grade, 1)
        if 3 * uln < max_alt <= 5 * uln:
            grade = max(grade, 2)
        if 5 * uln < max_alt <= 20 * uln:
            grade = max(grade, 3)
        if max_alt > 20 * uln:
            grade = max(grade, 4)

    # Bilirubin
    if max_bili is not None:
        uln = BILI_ULN_MGDL
        if 2 * uln < max_bili <= 3 * uln:
            grade = max(grade, 1)
        if 3 * uln < max_bili <= 5 * uln:
            grade = max(grade, 2)
        if 5 * uln < max_bili <= 10 * uln:
            grade = max(grade, 3)
        if max_bili > 10 * uln:
            grade = max(grade, 4)

    # QTc prolongation
    if baseline_qtc is not None:
        qtc_delta = qtc_delta or 0.0
        qtc_absolute = baseline_qtc + qtc_delta
        if qtc_absolute > 500 or qtc_delta > 60:
            grade = max(grade, 3)
        elif qtc_absolute > 480 or qtc_delta > 30:
            grade = max(grade, 2)
        elif qtc_absolute > 450 or qtc_delta > 0:
            grade = max(grade, 1)

    return grade


# ---------------------------------------------------------------------------
# Integrated DLT determination
# ---------------------------------------------------------------------------


def determine_dlt(
    observations: list[Observation],
    drug: Drug,
    thresholds: SafetyThresholds,
    patient_id: str,
) -> bool:
    """Determine whether a single patient experiences a DLT.

    A DLT is declared if any of the following hold:
    - absolute QTc > protocol qt_threshold
    - delta QTc > protocol qt_delta
    - Hy's Law criteria (ALT > alt_threshold x ULN AND bilirubin > bilirubin_threshold x ULN)
    - CTCAE grade >= 3 for ALT, bilirubin, or QTc
    """
    patient_obs = [o for o in observations if o.patient_id == patient_id]

    qtc_results = assess_qtc(
        patient_obs,
        drug,
        qt_threshold_delta=thresholds.qt_delta,
        qt_threshold_absolute=thresholds.qt_threshold,
    )
    dili_results = assess_dili(
        patient_obs,
        drug,
        alt_uln_mult=thresholds.alt_threshold,
        bili_uln_mult=thresholds.bilirubin_threshold,
    )

    if qtc_results:
        qtc_r = qtc_results[0]
        if qtc_r.flag_qtc_60ms_delta or qtc_r.flag_qtc_500ms_absolute:
            return True

    if dili_results:
        dili_r = dili_results[0]
        if dili_r.hy_law_criteria_met:
            return True

    max_alt = max((o.alt for o in patient_obs if o.alt is not None), default=None)
    max_bili = max((o.bilirubin for o in patient_obs if o.bilirubin is not None), default=None)

    qtc_result = qtc_results[0] if qtc_results else None
    grade = ctcae_dlt_grade(
        exposure=0.0,
        dose=0.0,
        max_alt=max_alt,
        max_bili=max_bili,
        baseline_qtc=qtc_result.baseline_qtc if qtc_result else None,
        qtc_delta=qtc_result.qtc_delta if qtc_result else None,
    )
    return grade >= 3


# ---------------------------------------------------------------------------
# Convenience: run safety assessment on a population
# ---------------------------------------------------------------------------


def run_safety_assessment(
    observations: list[Observation],
    drug: Drug,
    thresholds: SafetyThresholds | None = None,
) -> dict[str, Any]:
    """Run full safety assessment (QTc + DILI) on a population."""
    from insilico_trial.schemas import SafetyThresholds as _ST

    thresh = thresholds or _ST()
    qtc_results = assess_qtc(
        observations, drug,
        qt_threshold_delta=thresh.qt_delta,
        qt_threshold_absolute=thresh.qt_threshold,
    )
    dili_results = assess_dili(
        observations, drug,
        alt_uln_mult=thresh.alt_threshold,
        bili_uln_mult=thresh.bilirubin_threshold,
    )

    n_qtc_60ms = sum(1 for r in qtc_results if r.flag_qtc_60ms_delta)
    n_qtc_500ms = sum(1 for r in qtc_results if r.flag_qtc_500ms_absolute)
    n_hy_law = sum(1 for r in dili_results if r.hy_law_criteria_met)
    avg_dili_prob = sum(r.dili_probability for r in dili_results) / len(dili_results) if dili_results else 0.0

    return {
        "n_patients": len(qtc_results),
        "n_qtc_60ms_delta": n_qtc_60ms,
        "n_qtc_500ms_absolute": n_qtc_500ms,
        "n_dili_hy_law": n_hy_law,
        "avg_dili_probability": float(avg_dili_prob),
        "qtc_patients": [
            {"patient_id": r.patient_id, "baseline_ms": r.baseline_qtc,
             "max_ms": r.max_qtc, "delta_ms": r.qtc_delta,
             "flag_60ms": r.flag_qtc_60ms_delta, "flag_500ms": r.flag_qtc_500ms_absolute}
            for r in qtc_results
        ],
        "dili_patients": [
            {"patient_id": r.patient_id, "max_alt": r.max_alt, "max_bili": r.max_bilirubin,
             "hy_law": r.hy_law_criteria_met, "dili_prob": r.dili_probability}
            for r in dili_results
        ],
    }


__all__ = [
    "QTcResult",
    "DiliResult",
    "assess_qtc",
    "assess_dili",
    "ctcae_dlt_grade",
    "determine_dlt",
    "run_safety_assessment",
    "CTCAE_GRADES",
]
